title: "CUDA 2D Convolution Optimization"
description: "A step-by-step journey optimizing 2D convolution operations in CUDA"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: true
github:
  repository_url: https://github.com/gantech/convolution_cuda
